### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by moniquesch** [jonchang/phlawd#1]
Hello!
I am having some issues with the installation. I followed all the steps, including the requirements, but when I type "make" on the terminal prompt, the following errors are displayed:
![Captura de tela de 2019-04-22 17-07-05](https://user-images.githubusercontent.com/49883223/56525335-363ffc80-6521-11e9-8a0a-a5499d4d6626.png)
![Captura de tela de 2019-04-22 17-07-44](https://user-images.githubusercontent.com/49883223/56525336-363ffc80-6521-11e9-83ec-2d7b680b9027.png)

Thank you for your attention!

**Comment by jonchang** [comment]
Hi @moniquesch, I'm terribly sorry that I didn't see this until I was going through my open issues!

In the off chance that you still need this specific version of phlawd, please see follow along in https://github.com/brewsci/homebrew-bio/pull/1018. Once that is closed you can get phlawd working by [installing Homebrew](https://brew.sh) and then running `brew install brewsci/bio/phlawd`. Feel free to reply in this issue or email me (listed in my profile) if you need additional help.
